# Generated by Django 4.1.3 on 2022-11-04 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('atracoes', '0001_initial'),
        ('endereco', '0001_initial'),
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pontos_turistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('aprovado', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='django_rest')),
                ('atracoes', models.ManyToManyField(to='atracoes.atracao')),
                ('avaliacoes', models.ManyToManyField(to='avaliacoes.avaliacao')),
                ('comentarios', models.ManyToManyField(to='comentarios.comentario')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco')),
            ],
        ),
    ]
