# Generated by Django 4.1.3 on 2022-11-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('horaio_fun', models.TextField()),
                ('idade_minima', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='atracoes')),
            ],
        ),
    ]
